import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/features/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1600px',
    },
    extend: {
      spacing: {
        'card-sm': '1rem',
        'card-md': '1.25rem',
        'card-lg': '1.5rem',
        'card-xl': '2rem',
        'gap-sm': '0.75rem',
        'gap-md': '1rem',
        'gap-lg': '1.5rem',
        'section-sm': '2rem',
        'section-md': '2.5rem',
        'section-lg': '3rem',
      },
      colors: {
        canvas: 'var(--bg-canvas)',
        surface: {
          DEFAULT: 'var(--bg-surface)',
          hover: 'var(--bg-surface-hover)',
          active: 'var(--bg-surface-active)',
        },
        muted: 'var(--bg-muted)',
        elevated: 'var(--bg-elevated)',
        glass: {
          DEFAULT: 'var(--bg-glass)',
          heavy: 'var(--bg-glass-heavy)',
        },
        line: {
          soft: 'var(--line-soft)',
          strong: 'var(--line-strong)',
          focus: 'var(--line-focus)',
          glass: 'var(--line-glass)',
        },
        accent: {
          primary: 'var(--accent-primary)',
          hover: 'var(--accent-primary-hover)',
          soft: 'var(--accent-primary-soft)',
          'primary-muted': 'var(--accent-primary-muted)',
          'primary-dark': 'var(--accent-primary-dark)',
          secondary: 'var(--accent-secondary)',
          tertiary: 'var(--accent-tertiary)',
          success: 'var(--accent-success)',
          'success-soft': 'var(--accent-success-soft)',
          warning: 'var(--accent-warning)',
          'warning-soft': 'var(--accent-warning-soft)',
          danger: 'var(--accent-danger)',
          'danger-soft': 'var(--accent-danger-soft)',
          info: 'var(--accent-info)',
          'info-soft': 'var(--accent-info-soft)',
          purple: 'var(--accent-purple)',
          pink: 'var(--accent-pink)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          tertiary: 'var(--text-tertiary)',
          placeholder: 'var(--text-placeholder)',
          'on-accent': 'var(--text-on-accent)',
        },
        chat: {
          panel: 'var(--chat-panel-bg)',
          'panel-input': 'var(--chat-panel-input-bg)',
          'panel-hover': 'var(--chat-panel-hover-bg)',
          'panel-placeholder': 'var(--chat-panel-placeholder)',
        },
      },
      fontFamily: {
        serif: 'var(--font-serif)',
        sans: 'var(--font-sans)',
        mono: 'var(--font-mono)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        '4xl': 'var(--radius-4xl)',
        '5xl': 'var(--radius-5xl)',
        pill: 'var(--radius-pill)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        hero: 'var(--shadow-hero)',
        glass: 'var(--shadow-glass)',
        'glass-heavy': 'var(--shadow-glass-heavy)',
        float: 'var(--shadow-float)',
        'panel-side': 'var(--shadow-panel-side)',
      },
      backdropBlur: {
        xs: 'var(--blur-xs, 4px)',
        sm: 'var(--blur-sm)',
        md: 'var(--blur-md)',
        lg: 'var(--blur-lg)',
        xl: 'var(--blur-xl)',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '220ms',
        slow: '350ms',
        spring: '400ms',
        smooth: '280ms',
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'smooth': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      animation: {
        'fade-in': 'fadeIn 220ms cubic-bezier(0.4, 0, 0.2, 1)',
        'slide-up': 'slideUp 280ms cubic-bezier(0.34, 1.56, 0.64, 1)',
        'slide-in-left': 'slideInLeft 350ms cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-from-left': 'slideFromLeft 500ms cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-from-right': 'slideFromRight 500ms cubic-bezier(0.16, 1, 0.3, 1)',
        'ink-fade-in': 'inkFadeIn 400ms cubic-bezier(0.16, 1, 0.3, 1)',
        'typing-pulse': 'typingPulse 1.4s ease-in-out infinite',
        'modal-in': 'modalIn 280ms cubic-bezier(0.16, 1, 0.3, 1)',
        'modal-out': 'modalOut 180ms cubic-bezier(0.4, 0, 1, 1)',
        'overlay-in': 'overlayIn 200ms cubic-bezier(0.4, 0, 0.2, 1)',
        'segment-slide': 'segmentSlide 280ms cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      keyframes: {
        fadeIn: {
          from: { opacity: '0', transform: 'translateY(4px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        slideInLeft: {
          from: { opacity: '0', transform: 'translateX(-10px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        slideFromLeft: {
          from: { opacity: '0', transform: 'translateX(-16px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        slideFromRight: {
          from: { opacity: '0', transform: 'translateX(16px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        inkFadeIn: {
          from: { opacity: '0', transform: 'translateY(6px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        typingPulse: {
          '0%, 100%': { opacity: '0.4' },
          '50%': { opacity: '1' },
        },
        modalIn: {
          from: { opacity: '0', transform: 'scale(0.96) translateY(8px)' },
          to: { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        modalOut: {
          from: { opacity: '1', transform: 'scale(1) translateY(0)' },
          to: { opacity: '0', transform: 'scale(0.96) translateY(8px)' },
        },
        overlayIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        segmentSlide: {
          from: { transform: 'translateX(var(--segment-from, 0))' },
          to: { transform: 'translateX(var(--segment-to, 0))' },
        },
      },
    },
  },
  plugins: [],
}

export default config
