from __future__ import annotations

from .interop import stream_event_normalizer as _normalizer

ParsedStreamEvent = _normalizer.ParsedStreamEvent
build_truncated_stream_message = _normalizer.build_truncated_stream_message
extract_stream_delta = _normalizer.extract_stream_delta
extract_stream_reasoning_delta = _normalizer.extract_stream_reasoning_delta
extract_stream_stop_reason = _normalizer.extract_stream_stop_reason
extract_stream_terminal_response = _normalizer.extract_stream_terminal_response
extract_stream_truncation_reason = _normalizer.extract_stream_truncation_reason
parse_raw_stream_event = _normalizer.parse_raw_stream_event
